In [29]:
import numpy as np
import pandas as pd
import matplotlib as plt
import urllib.request
from pulp import *
from scipy import optimize
import math

%matplotlib inline

In [30]:
t = pd.read_csv('../result/slope.csv', index_col=0).T
v = pd.DataFrame(pd.read_excel('../result/lac.xlsx').mean()).T
v.columns = t.columns
slope = pd.concat([t, v])
slope = slope.rename(index={0:'Lactate'})
slope = pd.concat([slope, pd.DataFrame([22, 12.5, 17], columns=['Doubling Time'] , index=slope.columns).T])

In [31]:
Lac = np.array(slope.T['Lactate']/slope.T.mean()['Lactate'])
gr = np.array([np.log(2)/i for i in slope.T['Doubling Time']])
Gr = gr/gr.mean()

In [32]:
Gr/Gr[0]

array([1.        , 1.76      , 1.29411765])

In [33]:
Lac/Lac[0]

array([1.        , 5.86994594, 3.0120277 ])

In [34]:
t = pd.read_csv('../csv/stochastic_matrix.csv', index_col=0).fillna(0)

In [35]:
v = t.T[[
    'R00200', 'R00268', 'R00341', 'R00342', 'R00351',
    'R00405', 'R00658', 'R00703', 'R01015', 'R01049',
    'R01056', 'R01061', 'R01070', 'R01082', 'R01196', 
    'R01197', 'R01325', 'R01512', 'R01518', 'R01528',
    'R01529', 'R01641', 'R01786', 'R01830', 'R01899',
    'R01900', 'R02035', 'R02164', 'R02740', 'R04779'
]].T

for i in v.columns:
    if sum(v[i] == 0) == v.shape[0]:
        v = v.drop(i, axis=1)
        
v['C00007'] = pd.Series(np.zeros(v.shape[0]), index=v.index)
v['C00033'] = pd.Series(np.zeros(v.shape[0]), index=v.index)
v['C00092'] = pd.Series(np.zeros(v.shape[0]), index=v.index)
v['C00014'] = pd.Series(np.zeros(v.shape[0]), index=v.index)
v['C00025'] = pd.Series(np.zeros(v.shape[0]), index=v.index)

In [36]:
df = v.T
df['Glucose_input'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Glucose_input']['C00267'] = 1

df['Oxygen_input'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Oxygen_input']['C00007'] = 1

df['CO2_output'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['CO2_output']['C00011'] = -1

df['Lactate_output'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Lactate_output']['C00186'] = -1

df['Acetate_output'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Acetate_output']['C00033'] = -1

df['Glutamate_input'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Glutamate_input']['C00025'] = 1

df['Ammonia_input'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Ammonia_input']['C00014'] = 1

df['Glu_Exchange'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Glu_Exchange']['C00267'] = -1
df['Glu_Exchange']['C00092'] = 1

df['acetyl_CoA_hydrolase'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['acetyl_CoA_hydrolase']['C00024'] = -1
df['acetyl_CoA_hydrolase']['C00001'] = -1
df['acetyl_CoA_hydrolase']['C00010'] = 1
df['acetyl_CoA_hydrolase']['C00033'] = 1

df['NADP_Exchange'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['NADP_Exchange']['C00005'] = -1
df['NADP_Exchange']['C00003'] = -1
df['NADP_Exchange']['C00006'] = 1
df['NADP_Exchange']['C00004'] = 1

df['ADP_Exchange'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['ADP_Exchange']['C00002'] = -1
df['ADP_Exchange']['C00008'] = 1

df['AMP_Exchange'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['AMP_Exchange']['C00002'] = -1
df['AMP_Exchange']['C00020'] = -1
df['AMP_Exchange']['C00008'] = 2

df['R00835'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['R00835']['C00092'] = -1
df['R00835']['C00006'] = -1
df['R00835']['C01236'] = 1
df['R00835']['C00005'] = 1
df['R00835']['C00080'] = 1

df['R08575'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['R08575']['C05382'] = -1
df['R08575']['C00118'] = -1
df['R08575']['C00279'] = 1
df['R08575']['C00085'] = 1

df['R02164']['C00004'] = -1
df['R02164']['C00003'] = 1
df['R02164']['C15602'] = 0
df['R02164']['C15603'] = 0

df['R00243'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['R00243']['C00025'] = -1
df['R00243']['C00003'] = -1
df['R00243']['C00001'] = -1

df['R00243']['C00026'] = 1
df['R00243']['C00014'] = 1
df['R00243']['C00004'] = 1
df['R00243']['C00080'] = 1

df['Oxophos'] =  pd.Series(np.zeros(df.shape[0]), index=df.index)
df['Oxophos']['C00004'] = -2
df['Oxophos']['C00007'] = -1
df['Oxophos']['C00008'] = -5
df['Oxophos']['C00002'] = 5
df['Oxophos']['C00003'] = 2
df['Oxophos']['C00011'] = 1

In [37]:
BIOMASS = pd.read_csv('../csv/amino_acid.csv',index_col=0)
df_Biomass =  pd.Series(np.zeros(df.shape[0]), index=df.index)

for i in BIOMASS.index:
    df_Biomass[BIOMASS.T[i]['C_num']] = BIOMASS.T[i]['flux']
    
df_Biomass['C00668'] = -0.27519
df_Biomass['C00119'] = (-0.039036) + (-0.036117) + (-0.053446)

In [38]:
df_new = pd.concat([df_Biomass.T, df], axis=1)
df_new = df_new.rename(columns={0: 'BIOMASS'})
df_new = df_new.drop([
    'C00001','C00009','C00080','C00138','C00139','C15602','C15603', 
#     'C00231'
])

In [39]:
def fba(glc, ox):
    x = []
    for i in df_new.columns:
        if (
                (i=='Oxophos') or (i=='R01899') or (i=='R00268') or (i=='R10343') or (i=='R02164') or (i=='R00835') or 
                (i=='R02035') or (i=='ATP_Exchange') or (i=='AMP_Exchange') or (i=='CO2_output')
        ):
            x.append(LpVariable(i, lowBound=0,upBound=10000, cat='Continuous'))

        elif (i=='Lactate_output'):
            x.append(LpVariable(i, lowBound=0, upBound=10000, cat='Continuous'))
            
        elif (i=='BIOMASS'):
            x.append(LpVariable(i, lowBound=0, upBound=100, cat='Continuous'))
        
        elif (i=='Oxygen_input'):
            x.append(LpVariable(i, lowBound=ox, upBound=ox, cat='Continuous'))
        
        elif (i=='Glucose_input'):
            x.append(LpVariable(i, lowBound=glc, upBound=glc, cat='Continuous'))

        elif (i=='Glutamate_input'):
            x.append(LpVariable(i, lowBound=0, upBound=100, cat='Continuous'))
            
        elif (i=='Ammonia_input'):
            x.append(LpVariable(i, lowBound=-10000, upBound=10000, cat='Continuous'))
              
        elif (
            (i=='Succinate_output') or (i=='Malate_output') or (i=='Fumarate_output') or (i=='Acetate_output')
        ):
            x.append(LpVariable(i, lowBound=0, upBound=50, cat='Continuous'))
                
        elif (i=='R00200') or (i=='R01196') or (i=='R01197') or (i=='R00405'):
            x.append(LpVariable(i, lowBound=-10000, upBound=0, cat='Continuous'))

        else:
            x.append(LpVariable(i, lowBound=-10000, upBound=10000, cat='Continuous'))

    m = LpProblem(sense=LpMaximize)
    m += x[0]

    for i in np.dot(df_new, x):
        m += i == 0

    status = m.solve()
    if (LpStatus[status]) == 'Infeasible':
        print(i)
        return 100, 100

    y = []
    for i in x:
        y.append(i.value())

    j = pd.DataFrame(y, index=[str(i) for i in x]).T
    
    return np.array([j['BIOMASS'][0], j['Lactate_output'][0]])
#                      j['Ammonia_output'][0]])

In [40]:
def f(x):
    x1, x2, x3, y1, y2, y3 = x
    h =[
        fba(x1, y1), 
        fba(x2, y2), 
        fba(x3, y3)    
    ]
    
    p = pd.DataFrame(h, index=['Con', 'CloneA', 'CloneB'], columns=['Biomass', 'Lactate'])
    v = np.sum(np.abs(p['Biomass']/p['Biomass'].mean() - Gr)) + np.sum(np.abs(p['Lactate']/p['Lactate'].mean() - Lac))
    
    return v

In [41]:
x0 = list(slope.loc['Glucose'].values)+[0.01 for i in range(0, 3)]

In [42]:
x0

[0.0846460393271493,
 0.0378590327677735,
 0.014287987036586668,
 0.01,
 0.01,
 0.01]

In [43]:
res1 = optimize.minimize(
    f, 
    x0,
    method='Nelder-Mead'
)

In [44]:
res1

 final_simplex: (array([[0.00988934, 0.04031372, 0.02230024, 0.01149208, 0.01626085,
        0.0130115 ],
       [0.00988857, 0.04031964, 0.02230158, 0.01149357, 0.01626622,
        0.01300857],
       [0.00988635, 0.04031591, 0.02230359, 0.01149354, 0.01626468,
        0.0130116 ],
       [0.00988649, 0.0403099 , 0.0223037 , 0.01149584, 0.0162669 ,
        0.01301982],
       [0.00988625, 0.04031086, 0.02229899, 0.01149391, 0.01626469,
        0.01301055],
       [0.00988929, 0.04031712, 0.02230177, 0.01149366, 0.01626747,
        0.01300442],
       [0.00988783, 0.04032046, 0.02230207, 0.01149273, 0.01626326,
        0.01301083]]), array([0.21170289, 0.21173381, 0.21173605, 0.21174212, 0.21175402,
       0.21179324, 0.21179526]))
           fun: 0.21170288881494032
       message: 'Optimization terminated successfully.'
          nfev: 308
           nit: 192
        status: 0
       success: True
             x: array([0.00988934, 0.04031372, 0.02230024, 0.01149208, 0.01626085,
    

In [45]:
x1, x2, x3, y1, y2, y3 = res1.x

In [46]:
def fba_result(glc, ox):
    x = []
    for i in df_new.columns:
        if (
                (i=='Oxophos') or (i=='R01899') or (i=='R00268') or (i=='R10343') or (i=='R02164') or (i=='R00835') or (i=='R02035') or
                (i=='ATP_Exchange') or (i=='AMP_Exchange') or (i=='Glutamate_output') or (i=='CO2_output') or (i=='Ammonia_output')
        ):
            x.append(LpVariable(i, lowBound=0,upBound=10000, cat='Continuous'))

        elif (i=='Lactate_output'):
            x.append(LpVariable(i, lowBound=0, upBound=10000, cat='Continuous'))
            
        elif (i=='BIOMASS'):
            x.append(LpVariable(i, lowBound=0, upBound=100, cat='Continuous'))
        
        elif (i=='Oxygen_input'):
            x.append(LpVariable(i, lowBound=ox, upBound=ox, cat='Continuous'))
        
        elif (i=='Glucose_input'):
            x.append(LpVariable(i, lowBound=glc, upBound=glc, cat='Continuous'))

        elif (i=='Glutamate_input'):
            x.append(LpVariable(i, lowBound=0, upBound=100, cat='Continuous'))
            
        elif (i=='Ammonia_input'):
            x.append(LpVariable(i, lowBound=-10000, upBound=10000, cat='Continuous'))
              
        elif (
            (i=='Succinate_output') or (i=='Malate_output') or (i=='Fumarate_output') or (i=='Acetate_output')
        ):
            x.append(LpVariable(i, lowBound=0, upBound=50, cat='Continuous'))
                
        elif (i=='R00200') or (i=='R01196') or (i=='R01197') or (i=='R00405'):
            x.append(LpVariable(i, lowBound=-10000, upBound=0, cat='Continuous'))

        else:
            x.append(LpVariable(i, lowBound=-10000, upBound=10000, cat='Continuous'))

    m = LpProblem(sense=LpMaximize)
    m += x[0]

    for i in np.dot(df_new, x):
        m += i == 0

    status = m.solve()
    if (LpStatus[status]) == 'Infeasible':
        print(i)
        return

    y = []
    for i in x:
        y.append(i.value())

    j = pd.DataFrame(y, index=[str(i) for i in x]).T
    
    return j

In [47]:
result = pd.concat([fba_result(x1, y1).T, fba_result(x2, y2).T, fba_result(x3, y3).T], axis=1)
result.columns = ['Control', 'Clone A', 'Clone B']

In [48]:
# result.to_csv('../result/fba_abs.csv')

In [49]:
result

Control   Clone A   Clone B
BIOMASS               0.002848  0.004030  0.003225
R00200               -0.013259 -0.071403 -0.037219
R00268                0.000000  0.000000  0.000000
R00341               -0.001800 -0.002547 -0.002038
R00342                0.001023  0.001448  0.001158
R00351                0.000000  0.000000  0.000000
R00405                0.000000  0.000000  0.000000
R00658                0.015060  0.073950  0.039257
R00703               -0.011819 -0.069365 -0.035589
R01015               -0.008983 -0.039032 -0.021275
R01049                0.000366  0.000518  0.000415
R01056               -0.000244 -0.000345 -0.000276
R01061                0.017845  0.077891  0.042411
R01070                0.008983  0.039032  0.021275
R01082               -0.001023 -0.001448 -0.001158
R01196                0.000000  0.000000  0.000000
R01197                0.000000  0.000000  0.000000
R01325                0.000000  0.000000  0.000000
R01512               -0.017845 -0.077891 -0.042411
R01518               -0.015060 -0.073950 -0.039257
R01528                0.000000  0.000000  0.000000
R01529               -0.000244 -0.000345 -0.000276
R01641                0.000122  0.000173  0.000138
R01786                0.009889  0.040314  0.022300
R01830                0.000122  0.000173  0.000138
R01899                0.000000  0.000000  0.000000
R01900                0.000000  0.000000  0.000000
R02035                0.000000  0.000000  0.000000
R02164                0.000000  0.000000  0.000000
R02740                0.009106  0.039205  0.021413
R04779                0.008983  0.039032  0.021275
Glucose_input         0.009889  0.040314  0.022300
Oxygen_input          0.011492  0.016261  0.013012
CO2_output            0.008669  0.012266  0.009815
Lactate_output        0.011819  0.069365  0.035589
Acetate_output        0.000000  0.000000  0.000000
Glutamate_input       0.004225  0.005979  0.004784
Ammonia_input        -0.003202 -0.004531 -0.003626
Glu_Exchange          0.000000  0.000000  0.000000
acetyl_CoA_hydrolase -0.000133 -0.000188 -0.000150
NADP_Exchange         0.008925  0.012628  0.010105
ADP_Exchange          0.005823  0.060881  0.028799
AMP_Exchange          0.000366  0.000518  0.000415
R00835                0.000000  0.000000  0.000000
R08575               -0.000122 -0.000173 -0.000138
R00243                0.004225  0.005979  0.004784
Oxophos               0.011492  0.016261  0.013012

In [22]:
result.loc['BIOMASS']/result.loc['BIOMASS'][0]

Control    1.000000
Clone A    1.760117
Clone B    1.294255
Name: BIOMASS, dtype: float64

In [23]:
result.loc['Lactate_output']/result.loc['Lactate_output'][0]

Control    1.000000
Clone A    5.870009
Clone B    3.012105
Name: Lactate_output, dtype: float64

In [24]:
Gr/Gr[0]

array([1.        , 1.76      , 1.29411765])

In [25]:
Lac/Lac[0]

array([1.        , 5.86994594, 3.0120277 ])